#!/usr/bin/env python3
"""Emit Visibility-monitor rules for the production/ and cloud/ bundles.

One generator, two outputs, distinct prefixes — a collision between
production/ and cloud/ alert names has been fixed once in this repo already and
is not being reintroduced:

    production/prometheus/visibility-rules.yml   slo:        WorkflowSLO*
    cloud/prometheus/visibility-rules.yml        cloudslo:   CloudWorkflowSLO*

WHY THERE IS NO MULTIWINDOW BURN-RATE LADDER HERE
-------------------------------------------------
DESIGN.md originally specified one ("14.4x/6x page, 3x/1x ticket", matching the
existing bundles). It is not computable from what the monitor publishes, and
shipping it would have produced rules that silently never fire.

The existing bundles build burn rates from rate() over COUNTERS at several
window lengths. The monitor publishes point-in-time GAUGES over the full
slo_window (28d), overwritten in place on every poll. rate() on those is
meaningless, and there is no 1h or 6h view of the same measurement to compare
against — so the short-window half of every burn-rate pair does not exist.

What ships instead is error-budget *consumption* with threshold alerts, which is
computable from these gauges and answers the question that actually matters:
how much of the budget is left.

Restoring a true ladder requires the monitor to publish short-window closed
counts as well (a `short_window` config, queried on the fast loop). That is
tracked in DESIGN.md; it roughly doubles window-query cost, which is why it is a
decision rather than an oversight.

Usage: generate_visibility_rules.py            # write both bundles
       generate_visibility_rules.py --check    # verify committed files match
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BUNDLES = [
    {
        "path": ROOT / "production/prometheus/visibility-rules.yml",
        "record": "slo:",
        "alert": "WorkflowSLO",
        "label": "self-hosted",
    },
    {
        "path": ROOT / "cloud/prometheus/visibility-rules.yml",
        "record": "cloudslo:",
        "alert": "CloudWorkflowSLO",
        "label": "Temporal Cloud",
    },
]


def render(b):
    r, a = b["record"], b["alert"]
    return f'''# Workflow duration SLO rules — {b["label"]}
#
# GENERATED by tools/generate_visibility_rules.py. Do not edit by hand.
#
# These consume temporal_slo_* series from the Visibility monitor service
# (monitor/). They are useless without it running and scraped — see
# {a}MonitorStale, which is what tells you that has stopped being true.
#
# Runbook: monitor/RUNBOOK.md
#
# WHAT THESE COVER THAT NOTHING ELSE DOES
# Every other rule in this bundle is built on counters describing Workflows that
# ENDED. An execution that never ends increments none of them, so a Workflow
# stuck forever is invisible to all of them. These rules are the only ones that
# see it.

groups:
  - name: workflow-duration-slo
    interval: 30s
    rules:
      # Compliance over the SLO window.
      #
      # `sum without(bucket)` is LOAD-BEARING. over_budget_executions carries a
      # `bucket` label the closed gauges do not, and a Prometheus binary operator
      # requires identical label sets — without it this expression returns EMPTY
      # rather than a wrong number, which no panel or alert would report. This
      # was shipped broken in DESIGN.md until it was run against a live cluster.
      #
      # The third denominator term is the design's central property: an OPEN
      # execution past budget is already a violation and can never become
      # compliant, so it belongs in the denominator NOW. That is what makes
      # terminating a stuck Workflow fail to improve this number — verified:
      # 5 executions moved from over_budget{{bucket="1"}} to closed_over_budget
      # and compliance held at 0.793336 exactly.
      - record: {r}workflow_compliance:ratio
        expr: |
          temporal_slo_closed_in_budget
          /
          clamp_min(
            temporal_slo_closed_in_budget
            + temporal_slo_closed_over_budget
            + sum without(bucket) (temporal_slo_over_budget_executions{{bucket="1"}}),
            1
          )

      # Error budget remaining, as a fraction of the budget the objective allows.
      #
      # 1.0 = untouched, 0.0 = fully consumed, negative = objective missed.
      # The objective comes from temporal_slo_objective_ratio rather than being
      # hardcoded, so config and alerts cannot drift apart silently.
      #
      # `on(workflow_type) group_left()` is required, not decorative: compliance
      # carries task_queue as well as workflow_type, the objective carries only
      # workflow_type, and an unqualified division between different label sets
      # matches nothing. The matching modifier must also sit between two VECTORS —
      # writing `1 - on(...) group_left() temporal_slo_objective_ratio` is a parse
      # error, because the left side is a scalar. Hence the clamp_min wrapping the
      # subtraction rather than the whole term.
      - record: {r}workflow_budget_remaining:ratio
        expr: |
          1 - (
            (1 - {r}workflow_compliance:ratio)
            / on(workflow_type) group_left()
            clamp_min(1 - temporal_slo_objective_ratio, 0.0001)
          )

      # ----------------------------------------------------------------------
      # Alerts
      # ----------------------------------------------------------------------

      # Stuck executions are NOT a burn-rate concern. There is no acceptable
      # steady-state rate of non-determinism, poison payloads or bad deploys, so
      # this pages on any sustained non-zero value rather than on a budget trend.
      #
      # Published only where TemporalReportedProblems exists (Server 1.30+).
      # Where it does not, the series is ABSENT and this rule is silent — which
      # is why {a}StuckDetectionUnavailable exists as a separate signal.
      - alert: {a}Stuck
        expr: sum by (workflow_type, task_queue, cause) (temporal_slo_stuck_executions) > 0
        for: 15m
        labels:
          severity: critical
          component: workflow-slo
        annotations:
          summary: "{{{{ $value }}}} {{{{ $labels.workflow_type }}}} executions stuck ({{{{ $labels.cause }}}})"
          description: "Temporal reports these executions as not making progress. cause=WorkflowTaskFailed usually means a code bug (check for TMPRL1100 non-determinism in logs); cause=WorkflowTaskTimedOut usually means the Worker cannot finish the task in time. These do not self-heal. See monitor/RUNBOOK.md."

      - alert: {a}ExecutionsOverBudget
        expr: sum without(bucket) (temporal_slo_over_budget_executions{{bucket="2"}}) > 0
        for: 10m
        labels:
          severity: warning
          component: workflow-slo
        annotations:
          summary: "{{{{ $value }}}} {{{{ $labels.workflow_type }}}} executions past 2x duration budget"
          description: "OPEN executions exceeding twice their budget. No counter-based alert can see these. Get the IDs from Visibility — there is deliberately no workflow_id label. Do NOT terminate them to clear this alert: the SLI counts them already, so terminating moves them between denominator terms and changes nothing. See monitor/RUNBOOK.md."

      - alert: {a}BudgetLow
        expr: {r}workflow_budget_remaining:ratio < 0.25
        for: 30m
        labels:
          severity: warning
          component: workflow-slo
        annotations:
          summary: "{{{{ $labels.workflow_type }}}} duration budget below 25%"
          description: "Executions are finishing late often enough to consume the error budget for this window. Threshold, not burn rate — see the header of this file for why a multiwindow ladder is not computable from these series."

      - alert: {a}BudgetExhausted
        expr: {r}workflow_budget_remaining:ratio <= 0
        for: 15m
        labels:
          severity: critical
          component: workflow-slo
        annotations:
          summary: "{{{{ $labels.workflow_type }}}} duration objective missed for this window"
          description: "The duration objective is no longer being met over the compliance window. Freeze risky changes to this Workflow type and work the backlog of late executions."

      # The guard on the whole group, and it is not optional.
      #
      # The monitor deliberately never publishes a zero when a Visibility query
      # fails — a 0 would read as "nothing is over budget" during exactly the
      # outage when that is least likely to be true. The cost of that choice is
      # that a frozen gauge looks healthy, so freshness must be alerted
      # separately. Removing this rule while keeping that behaviour turns the
      # design's safest property into a silent failure.
      - alert: {a}MonitorStale
        expr: time() - temporal_slo_last_successful_poll_timestamp_seconds > 300
        for: 5m
        labels:
          severity: critical
          component: workflow-slo
        annotations:
          summary: "SLO monitor polls stale for {{{{ $labels.workflow_type }}}} ({{{{ $labels.query_kind }}}})"
          description: "Visibility queries have not succeeded for over 5 minutes. Every temporal_slo_* gauge is showing its LAST KNOWN value, not current state. Treat the duration SLI as unavailable, not as good news. Check temporal_slo_poll_errors_total for the error_type."

      # Fires on the signal being unavailable, not on it reporting zero.
      - alert: {a}StuckDetectionUnavailable
        expr: temporal_slo_stuck_detection_available{{method="reported_problems"}} == 0
        for: 30m
        labels:
          severity: info
          component: workflow-slo
        annotations:
          summary: "Server-reported stuck detection unavailable in {{{{ $labels.namespace }}}}"
          description: "TemporalReportedProblems is not available, so stuck_executions is not published at all — absence rather than a misleading zero. Needs Server 1.30+ and, self-hosted, system.numConsecutiveWorkflowTaskProblemsToTriggerSearchAttribute. Duration buckets still work and remain the primary signal."
'''


def main():
    check = "--check" in sys.argv
    failed = False
    for b in BUNDLES:
        out = render(b)
        if check:
            if not b["path"].exists() or b["path"].read_text() != out:
                print(f"STALE: {b['path'].relative_to(ROOT)} — re-run generate_visibility_rules.py")
                failed = True
            else:
                print(f"  ok  {b['path'].relative_to(ROOT)}")
        else:
            b["path"].parent.mkdir(parents=True, exist_ok=True)
            b["path"].write_text(out)
            print(f"  wrote {b['path'].relative_to(ROOT)}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
